version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fakenews-backend
    ports:
      - "8000:80"

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    container_name: fakenews-frontend
    ports:
      - "7860:7860"
    environment:
      - USE_DOCKER=true
    depends_on:
      - backend